FROM alpine:3.12



#install nodejs then download and extract tokei. Install nodemon for development hotreloading.
RUN echo =========DEBUG BUILD========= \
&& apk add npm nodejs git \ 
&& wget -O tokei.tar.gz "https://github.com/XAMPPRocky/tokei/releases/download/v12.0.4/tokei-x86_64-unknown-linux-musl.tar.gz" \
&& tar -xzf tokei.tar.gz \
&& rm tokei.tar.gz \ 
&& mv ./tokei /bin/ \
&& npm install -g nodemon

WORKDIR /code
VOLUME [ "/code" ]

EXPOSE 3000
CMD [ "npm", "start"]


